import { DEVELOPMENT_ENV_NAME, PRODUCTION_ENV_NAME } from './env';

const DEVELOPMENT_API_PATH = 'https://kk.com';
const PRODUCTION_API_PATH = 'https://kk.com';

const API_PATHS = {
  [DEVELOPMENT_ENV_NAME]: DEVELOPMENT_API_PATH,
  [PRODUCTION_ENV_NAME]: PRODUCTION_API_PATH,
};

export { DEVELOPMENT_API_PATH, PRODUCTION_API_PATH, API_PATHS };
